### ISSUE TITLE
Specifying --translate-asm should emit #![feature(asm)]

### ISSUE THREAD

**Issue by thedrow** [immunant/c2rust#106]
When using `c2rust transpile --emit-build-files --translate-asm compile_commands.json`
the crate's main file `c2rust-lib.rs` does not contain the `#![feature(asm)]` which causes the build to fail.

If the `--translate-asm` option is specified this feature should be enabled automatically.

**Comment by TheDan64** [comment]
Do you have c2rust installed from crates.io? I believe we've since gotten rid of the `--translate-asm` flag here on master and it now translates automatically. The feature attr also gets added. You could cargo install from the sources here on git if you want immediate access to those changes. We haven't yet decided when to push a new version to crates.io

**Comment by thedrow** [comment]
I installed c2rust from cargo due to #107.
I'll test again.

**Comment by thedrow** [comment]
Yes this is resolved.
I'm waiting for a new release :)

**Comment by TheDan64** [comment]
We're currently working on updating c2rust to a newer nightly, so that we can improve our support for C-like variadic arguments. Then we should be good to go to do a new release
