### ISSUE TITLE
`CARGO_TARGET_DIR` is not considered in `gen_command_docs.py`

### ISSUE THREAD

**Issue by crlf0710** [immunant/c2rust#159]
`c2rust-refactor/doc/gen_command_docs.py` assumes target dir is always at this directory, which is actually not true.

**Comment by crlf0710** [comment]
Also, in `c2rust-refactor` README file, the link to commands list is broken.

**Comment by rinon** [comment]
Thanks for catching this. Yeah, `gen_command_docs.py` should respect `CARGO_TARGET_DIR`. The link to the commands list is broken on github, but this is the only way it works for the manual (since the command reference is auto-generated). I'd like to fix that, but haven't thought of a good way to make it work in both places.

For now, you can see the manual at https://c2rust.com/manual/c2rust-refactor/commands.html

**Comment by kkysen** [comment]
Closing as `c2rust refactor` in its current form is no longer being developed.
