### ISSUE TITLE
`c2rust refactor remove_redundant_casts` breaks compilation on 32-bit because of literal suffixes

### ISSUE THREAD

**Issue by jrmuizel** [immunant/c2rust#298]
The following code:
```c
size_t insertion_sort() {
    return 5;
}
```
translates to:
```rust
pub unsafe extern "C" fn insertion_sort() -> size_t {
    return 5 as libc::c_int as size_t;
}
```
Running `c2rust refactor remove_redundant_casts` gives
```rust
pub unsafe extern "C" fn insertion_sort() -> size_t {
    return 5u64;
}
```
Rewriting the literal as `5u64` breaks compilation on 32bit where `size_t` becomes `u32`

**Comment by jrmuizel** [comment]
It seems like this could be avoided by retyping size_t to usize before running `remove_redundant_casts` Is there a guide for recommended refactorings and the order they should be run?

**Comment by ahomescu** [comment]
> It seems like this could be avoided by retyping size_t to usize before running remove_redundant_casts

The problem is that those aren't the same Rust types (`usize` is a different type from whatever `size_t` aliases to), so it's not always a sound retyping without additional casts (although the sizes of the types generally match).

>  Is there a guide for recommended refactorings and the order they should be run?

That's definitely something we want to sit down and write, but never got around to.

**Comment by kkysen** [comment]
Closing as `c2rust refactor` in its current form is no longer being developed.
