### ISSUE TITLE
Problem with libc::c_ulong type on different platforms

### ISSUE THREAD

**Issue by HaronK** [immunant/c2rust#30]
It seems that libc::c_ulong and related types don't have same size on a different platforms. Documentation clearly states this: https://doc.rust-lang.org/std/os/raw/type.c_ulong.html
In my case on Linux everything works properly but on Windows I have a problem with casting function pointer to c_ulong.
Can we use just usize/isize in such a cases?

**Comment by TheDan64** [comment]
u/isize is pointer width size, but ulong is platform determined, so they don't really seem equivalent. It almost seems like the C code you're translating should instead be using s/size_t, which is roughly analogous to i/usize?

In any case, we currently translate integers exactly to their libc counterparts so that we can be as true to the original C as possible. See #3. Which makes me wonder, does the C code even work on windows for the same reason you've stated? I would expect it to have the same issue

**Comment by HaronK** [comment]
It's my [project](https://github.com/HaronK/lua-rs) of converting Lua to Rust. So C code definitely compiles under all platforms.
I just checked and it definitely **size_t** type from the C standard library where it's defined as **long unsigned int**. But now when c2rust converts it to libc::c_ulong I have a problem because as it said in the documentation (see the link in my first message) it can be **u64** or **u32** on the different platforms. And that's exactly what I have: on Linux it is **u64** and on Windows it is **u32**.

**Comment by glguy** [comment]
Translation with C to Rust happens after the C preprocessor has run. This means that some platform specific information can be baked into the translation from the machine that hosted the translation.

For cases like using Rust's `isize` and `usize` types, we're actively working on refactoring tool support to help update code.

**Comment by HaronK** [comment]
I've fixed this issue with types. I created types.rs file where I defined types equivalent to libc::c_* and replaced libc specific types everywhere in the project with a new one. This way I got centralized place with core types and I easily fixed my problem.
I think c2rust can also go this or similar way.

**Comment by rinon** [comment]
Closing this for now. We're aware of platform dependent type definitions, and don't have a good way to deal with this until we support macro `#ifdef`s, which is in progress.
