### ISSUE TITLE
Incorrect "Reached end of non-void function without returning"

### ISSUE THREAD

**Issue by kornelski** [immunant/c2rust#317]
In some cases (I guess when type of returned expression depends on function's return type) `return` is replaced with 

```rust
panic!("Reached end of non-void function without returning");
```

For example c2rust thinks these functions don't have a final `return` statement, and loses the returned value:

```c
float f()
{
    if (0)
        return 0
    else
        return 0
}
```

A second example is C++, but c2rust doesn't reject it as invalid, just generates the same kind of incorrect code.

```c++
struct X {};

struct X f()
{
    return {};
}
```

Output:

```rust
#![allow(dead_code, mutable_transmutes, non_camel_case_types, non_snake_case,
         non_upper_case_globals, unused_assignments, unused_mut)]
#![register_tool(c2rust)]
#![feature(register_tool)]
#[derive(Copy, Clone)]
#[repr(C)]
pub struct X {
}
#[no_mangle]
pub unsafe extern "C" fn f() -> X {
    panic!("Reached end of non-void function without returning");
}
```

Tested with c2rust.com.

**Comment by cdmistman** [comment]
> For example c2rust thinks these functions don't have a final `return` statement, and loses the returned value:

That seems to be a compiler optimization. You're missing semicolons! The output of `clang -Xclang -ast-dump` given your first function returns an ast that looks like:
```C
float f()
{
    if (0)
        return 0;
}
```
Since `if (0)` never evaluates, `c2rust` doesn't include it in the output, and there's no unconditional return as recognized by the clang parser, so the output is as-expected here. Even though the file still has incorrect syntax, `c2rust` *does* transpile as-expected if you put a `;` after the first `return 0`, since the clang parser is then able to recognize the `else` branch (`c2rust` also gives expected output with both missing semicolons included).

The second function is *also* invalid C: `{}` in a return statement expects an expression within. To change that code to valid C that `c2rust` can properly transpile, you need to change it to:
```C
struct X {};

struct X f()
{
  struct X x = {}; // the RHS here is really unnecessary
  return x;
}
```

**Comment by kornelski** [comment]
You're right about the semicolons. Unfortunately, it's been a while, so I don't remember where I got this C code from.
