### ISSUE TITLE
_mm_slli_si128 breaks translation

### ISSUE THREAD

**Issue by jrmuizel** [immunant/c2rust#32]
The following code fails to translate:
```c
#include <stdbool.h>
#include <stdint.h>
#include <tmmintrin.h>

void accumulate_non_zero_c(uint8_t *dst, int16_t *src, int len) {
    int i = 0;
    while (true) {
        __m128i a = _mm_loadu_si128((__m128i *) &src[i]);
        a = _mm_slli_si128(a, 2);
        _mm_storel_epi64((__m128i *) &dst[i], a);
        i += 8;
        /* breaking here saves one shuffle */
        if (i >= len)
            break;
    }
}
```

Removing 'a = _mm_slli_si128(a, 2);' makes it work

**Comment by TheDan64** [comment]
So the issue here is that most of the shuffle vector functions are really macros that call a super builtin function and so they need to be handled individually. I've already added support for a lot of shuffle vectors upstream, and I've just added `_mm_slli_si128` too. This should be available when we next update this repo.

The weird thing is that intel's docs for [_mm_slli_si128](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_slli_si128&expand=5236,3954,5288) doesn't seem to at all mention anything about shuffle vectors like it does for the other ones I've been seeing.

Anyway, if you find any more of these problematic shuffle vectors, please feel free to report them. I'll see if I can find any more shuffle vectors that aren't documented as such.

**Comment by TheDan64** [comment]
The fix should be available now. Please feel free to reopen if you have any more issues
