### ISSUE TITLE
Release binaries

### ISSUE THREAD

**Issue by thedrow** [immunant/c2rust#334]
It'd be much easier to use c2rust if it had binary releases you can install.

**Comment by nyanpasu64** [comment]
You could try running a Docker image at https://hub.docker.com/r/immunant/c2rust/tags. The most recently updated is `archlinux-base-latest`, but I don't know what version of c2rust that ships. I didn't actually try using this, because it's nearly 1 gigabyte to download. If you want to try, you need `immunant/c2rust:archlinux-base-latest`. Either `docker pull immunant/c2rust:archlinux-base-latest` or `./docker_run.sh immunant/c2rust:archlinux-base-latest`

The instructions at https://c2rust.com/manual/docker/ don't work, since there's no `ubuntu-xenial-20190131` tag anymore.

**Comment by chrysn** [comment]
The c2rust images in the immunant containers contain, as far as I can tell, only everything necessary to *build* c2rust (which is valuable on its own), not *binaries* of c2rust and its tools.

I think this is a duplicate of #326.

**Comment by thedrow** [comment]
@chrysn Yes, you're right.
