### ISSUE TITLE
use of undeclared crate or module `libc`

### ISSUE THREAD

**Issue by user95f85f** [immunant/c2rust#458]
I'm on Debian stable.

i have this installed on my system:
`dpkg -l | grep librust`
ii  librust-libc+rustc-dep-of-std-dev:amd64         0.2.80-1                         amd64        Rust bindings to libc - feature "rustc-dep-of-std"
ii  librust-libc+rustc-std-workspace-core-dev:amd64 0.2.80-1                         amd64        Rust bindings to libc - feature "rustc-std-workspace-core"
ii  librust-libc-dev:amd64                          0.2.80-1                         amd64        Rust bindings to libc - Rust source code
ii  librust-rustc-std-workspace-core-dev:amd64      1.0.0-1+b1                       amd64        Explicitly empty crate for rust-lang/rust integration - Rust source code

I put my C code into: https://c2rust.com/
Put the file into ~/whatever.rs
Went `rustc whatever.rs`
And the first error is:
`  |
7 |     fn puts(__s: *const libc::c_char) -> libc::c_int;
  |                         ^^^^ use of undeclared crate or module libc`

I can't do this.

**Comment by kkysen** [comment]
[c2rust.com](https://c2rust.com/) is currently using an outdated version of `c2rust`, but that shouldn't be the issue here.  You can install the latest version with `cargo install rust` as described in our [README](./README.md).

The issue you're seeing with `libc` is because `c2rust` uses the C types from the `libc` crate (as does `std`).  I think there may be an option to tell `c2rust transpile` to use the C types in `std` or `core`, but it uses the `libc` ones by default.  To fix this, you should add `libc = "0.2"` to your `Cargo.toml` dependencies, and then it should all work if you use `cargo` to compile your Rust code, which is probably what you want to do instead of using `rustc` directly.

**Comment by rinon** [comment]
Typo above, `cargo install c2rust`, but yeah, exactly. @user95f85f you should try using cargo rather than rustc directly. See https://doc.rust-lang.org/cargo.
