### ISSUE TITLE
Fix some `if cfg!(unix)` mis-usages

### ISSUE THREAD

**Issue by kkysen** [immunant/c2rust#708]
See https://github.com/immunant/c2rust/pull/519#issuecomment-1278853657 by @SimonIT.

I used `if cfg!(unix)` wrong (instead of `#[cfg(unix)]`), so some simple snippets don't compile on non-unix platforms anymore.

This is in `c2rust-build-paths/src/lib.rs` and `dynamic_instrumentation/src/main.rs`.

**Comment by MurraySobol** [comment]
Thanks for fixing this particular Windows error, I understand that there are (probably) several further Windows 11 errors to be fixed at some time.
Baby steps before giant leaps!!
BTW: I just reran  "cargo install c2rust" and got a similar, but I think a slightly different error:
    Compiling c2rust-build-paths v0.18.0
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> C:\Users\murra\.cargo\registry\src\index.crates.io-6f17d22bba15001f\c2rust-build-paths-0.18.0\src\lib.rs:35:26
   |
35 |             use std::os::unix::ffi::OsStrExt;
   |                          ^^^^ could not find `unix` in `os`

error[E0599]: no function or associated item named `from_bytes` found for struct `OsStr` in the current scope
  --> C:\Users\murra\.cargo\registry\src\index.crates.io-6f17d22bba15001f\c2rust-build-paths-0.18.0\src\lib.rs:37:20
   |
37 |             OsStr::from_bytes(path)
   |                    ^^^^^^^^^^ function or associated item not found in `OsStr`

I noted that it was trying to install this:
C:\>cargo install c2rust
    Updating crates.io index
  Installing c2rust v0.18.0
 I assume that this means that I should wait for the next official update of Rust, since this change wouldn't be merged into the current build?

Thanks again for all of your efforts.

**Comment by kkysen** [comment]
Hi!  It doesn't have anything to do with the version of rust itself, but you'd have to wait for the next release of `c2rust` to be able to `cargo install c2rust` the newest version.  But you can `cargo install --git https://github.com/immunant/c2rust/` and it'll build the latest `master` version, which includes the above fix.

**Comment by MurraySobol** [comment]
Thanks, I really appreciate this.

I followed your instructions re: cargo install and progressed further but got this error:
   Compiling clap_derive v3.2.25
error: failed to run custom build command for `c2rust-ast-exporter v0.18.0 (C:\Users\murra\.cargo\git\checkouts\c2rust-2a3ef4c32beab81a\431847a\c2rust-ast-exporter)`

Caused by:
  process didn't exit successfully: `C:\Users\murra\AppData\Local\Temp\cargo-install0BdKSm\release\build\c2rust-ast-exporter-65bc7a58e81af1f8\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at c2rust-build-paths\src\lib.rs:88:44:
  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }

It appears that a file is missing??

Thanks for you help!!

Murray
________________________________
