### ISSUE TITLE
static analysis does not support `std::mem::size_of` or other unknown functions

### ISSUE THREAD

**Issue by aneksteind** [immunant/c2rust#734]
In the following example:

```rust
unsafe extern "C" fn fdnode_init() -> *mut fdnode {
    let fdn: *mut fdnode = calloc(
        1 as libc::c_int as libc::c_ulong,
        ::std::mem::size_of::<fdnode>() as libc::c_ulong,
    ) as *mut fdnode;
    if fdn.is_null() {
        println!("It's null");
    }
    let x = fdevents {
        fdarray: 0 as *mut *mut fdnode,
    };
    return fdn;
}
```

the static analyzer panics:

```
visit_terminator(_7 = std::mem::size_of::<fdnode_st>() -> [return: bb1, unwind: bb14])
callee = Some(Other { def_id: DefId(2:2156 ~ core[480a]::mem::size_of), substs: [fdnode_st] })
thread 'rustc' panicked at 'not yet implemented: call to unknown function DefId(2:2156 ~ core[480a]::mem::size_of)', c2rust-analyze/src/dataflow/type_check.rs:308:21
```

**Comment by spernsteiner** [comment]
I think it's safe for the analysis to ignore functions that don't take or return pointers, such as `size_of`.  This could be done either by checking for it directly in the existing `Callee::Other` cases, or by adding a new `Callee::OtherNonPtr` variant which can be handled separately (hopefully the handling should be trivial) in places that match on a `Callee`.

**Comment by kkysen** [comment]
What counts as an unknown function according to `c2rust-analyze`?

**Comment by spernsteiner** [comment]
>What counts as an unknown function according to c2rust-analyze?

Any extern or library function that isn't specifically known to the analysis.  It can handle calls to other functions in the current crate (since it can see the body and the `PointerId`s for the signature), and can handle the library functions like `offset` that are recognized in `util::builtin_callee`, but it will fail on anything else.  Ideally, every library function used by `c2rust-transpile` should eventually be added to `util::builtin_callee`.

Obviously this approach is not great for dealing with partially-refactored code - for that case, we might eventually want to add some handling for functions that already have a completely safe signature.

**Comment by kkysen** [comment]
That seems unwieldy to have to account for every library function.  We can't see into those functions at all?  Especially if they are `const fn`s and compile down to an intrinsic (maybe just handle intrinsics).
