### ISSUE TITLE
Make `f128` crate and struct be a command line option

### ISSUE THREAD

**Issue by LegNeato** [immunant/c2rust#745]
As it is, code with `long double` includes an unmaintained crate that only works on Linux (and may even be broken there): [`f128`](https://github.com/jkarns275/f128). It looks like [`rust_decimal`](https://docs.rs/rust_decimal/latest/rust_decimal) with the [`c_repr`](https://docs.rs/rust_decimal/latest/rust_decimal/#c-repr) feature could be a potential path forward.

Related to #154.

**Comment by kkysen** [comment]
A few points:

* [`f128`](https://github.com/jkarns275/f128) is not unmaintained; the `README.md` says ["This crate is currently in maintenance mode."](https://github.com/jkarns275/f128/blob/f0d51bd5fc0d1b9b526820bd5a92b97f3593124f/README.md#L4).

* `long double` in C can map to very different things.  `msvc` uses `double` for `long double`, for example (though we don't support Windows at all at this point).  So trying to have good cross-platform behavior with `long double` is really hard, and `c2rust transpile` doesn't have a good cross-platform story in the first place due to the preprocessor.

* I'm confused how [`rust_decimal`](https://docs.rs/rust_decimal/latest/rust_decimal) could help, though.  It looks like it's for a 96-bit decimal representation, while `long double` is often `f128` aka IEEE754 `binary128`.  Am I misreading things?

* Given `f128` is not a community standard at all, and until there is an `f128` or `long double` (`c_long_double`) in `std`/`core`, we could also make what crate and struct gets used for `f128` support be a command-line option.
