### ISSUE TITLE
Test `c2rust-analyze` on `lighttpd-minimal`

### ISSUE THREAD

**Issue by kkysen** [immunant/c2rust#754]
Part of #728.

This should be tested as part of `cargo test -p c2rust-analyze` and in CI.  Note that it doesn't need `FileCheck`.  We should just need to check that `c2rust-analyze` runs without crashing on `lighttpd-minimal/src/main.rs`.

**Comment by kkysen** [comment]
@aneksteind and @spernsteiner, would snapshot tests for the `c2rust-analyze` output here be useful at all?  Or is that too volatile?  I do like how it helps you track changes to the output, and it's useful during review.  Otherwise, I'll only be checking if it doesn't crash, and ignoring the output completely.

**Comment by spernsteiner** [comment]
I'd expect the output to be quite volatile.  For example, minor changes to the input program can affect `PointerId` numbering across the entire crate.  `FileCheck` works well for testing this, since it lets you regex-match any `PointerId`, or even capture a `PointerId` and assert that the same `PointerId` appears on a later line.

I think it's fine for now to just check that the tool doesn't crash.  Later we can write some FileCheck assertions about the output.

**Comment by kkysen** [comment]
- Fixed by #772.
