### ISSUE TITLE
Facing transpilation issues around Atomic

### ISSUE THREAD

**Issue by mahajpuneet** [immunant/c2rust#832]
Hi team, 

Trying to use c2rust, but noticing these issues:

`--> /usr/lib/llvm-11/lib/clang/11.0.1/include/stdatomic.h:107:1
 [-Wclang-ast]
thread 'main' panicked at 'Unsupported implicit cast: AtomicToNonAtomic', /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/c2rust-transpile-0.17.0/src/c_ast/conversion.rs:165:14`

Could you please advise? Thanks in advance

**Comment by thedataking** [comment]
C11 atomics are not fully supported so what you are seeing is expected. We do have a *highly experimental* branch that you can try out https://github.com/immunant/c2rust/pull/814 which may translate the input that triggers the above error. Since the branch is WIP, please audit the output Rust carefully and expect errors.

**Comment by mahajpuneet** [comment]
Sure @thedataking, thank you. Sorry, is this branch likely to be merged perhaps in a month or two? Can wait

**Comment by thedataking** [comment]
Adding support for C11 atomics is not high priority so unfortunately, I do not have a timeframe for merging it in. If you are translating an open source project, let me know which ones and I can try to see if the branch handles all items you need.
