### ISSUE TITLE
Support other legacy languages through ROSE

### ISSUE THREAD

**Issue by XVilka** [immunant/c2rust#91]
ROSE compiler is famous programming language transformation tool. While their repository is somewhat unstructured, it has quite good support for translating languages like
- COBOL
- JOVIAL
- MATLAB
- Fortran  (while it is not legacy, some projects migrate from it)
- Ada (while it is not legacy, some projects migrate from it)

It might be useful to cooperate with LLNL to create the way for COBOL -> Rust transition, without spending decades of fighting with memory problems in case of using C as a middleman.

See https://github.com/rose-compiler/rose/issues/37

**Comment by mardab** [comment]
I can already imagine legacy COBOL systems being moved into safe, concurrent Rust, great idea!

**Comment by rinon** [comment]
We actually considered ROSE when we started this project. We decided against using it because we wanted to focus on only C code, and wanted to build the transpiler itself in Rust. This meant we only needed a C frontend, and so decided to use Clang directly.

Making c2rust more modular to support additional input ASTs would require a substantial rewrite, since we transform the C AST directly into Rust AST, without a generic IR. If were to rewrite the transpiler to use ROSE AST instead, I could see this working, but I know the core team isn't going to have time to do this in the foreseeable future.

**Comment by XVilka** [comment]
There is also [interesting project](https://github.com/aschoerk/converter-page) of translating Java to Rust. While it is written in Java itself (why not to use it to convert the code its own code haha?), but can be somehow integrated with everything else, except the transpiler crate, leveraging the refactoring facilities.
